# Based on:
# https://github.com/pgf-tikz/pgf/blob/master/.github/workflows/check.yml
# See also:
# https://github.com/gusbrs/zref-clever/pull/15#issue-1590334483
# https://gitlab.com/islandoftex/images/texlive
# https://tex.stackexchange.com/a/459486

# For an alternative to the IoT docker images:
# https://github.com/josephwright/siunitx/blob/main/.github/workflows/main.yaml
# https://github.com/zauguin/install-texlive
# https://github.com/moewew/biblatex-ext/blob/dev/.github/workflows/l3build.yml

name: CI l3build test suite

on: [push, pull_request]

jobs:
  tests:
    name: Regression tests

    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Update TeX Live
        run: tlmgr update --self --all

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: l3build check -q --show-log-on-error

      - name: Archive failed test output
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-diff-files
          path: build/test*/*.diff

  doc:
    name: Documentation

    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Update TeX Live
        run: tlmgr update --self --all

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile documentation
        run: l3build doc -q
